package dao;
// Generated 12/jun/2018 12:19:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localtrabalho generated by hbm2java
 */
public class Localtrabalho  implements java.io.Serializable {


     private byte idlocaltrabalho;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

    public Localtrabalho() {
    }

	
    public Localtrabalho(byte idlocaltrabalho) {
        this.idlocaltrabalho = idlocaltrabalho;
    }
    public Localtrabalho(byte idlocaltrabalho, Set<Funcionario> funcionarios) {
       this.idlocaltrabalho = idlocaltrabalho;
       this.funcionarios = funcionarios;
    }
   
    public byte getIdlocaltrabalho() {
        return this.idlocaltrabalho;
    }
    
    public void setIdlocaltrabalho(byte idlocaltrabalho) {
        this.idlocaltrabalho = idlocaltrabalho;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }




}


