package dao;
// Generated 12/jun/2018 12:19:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localidade generated by hbm2java
 */
public class Localidade  implements java.io.Serializable {


     private short idlocalidade;
     private String nome;
     private Set<Armazem> armazems = new HashSet<Armazem>(0);
     private Set<Loja> lojas = new HashSet<Loja>(0);

    public Localidade() {
    }

	
    public Localidade(short idlocalidade, String nome) {
        this.idlocalidade = idlocalidade;
        this.nome = nome;
    }
    public Localidade(short idlocalidade, String nome, Set<Armazem> armazems, Set<Loja> lojas) {
       this.idlocalidade = idlocalidade;
       this.nome = nome;
       this.armazems = armazems;
       this.lojas = lojas;
    }
   
    public short getIdlocalidade() {
        return this.idlocalidade;
    }
    
    public void setIdlocalidade(short idlocalidade) {
        this.idlocalidade = idlocalidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Armazem> getArmazems() {
        return this.armazems;
    }
    
    public void setArmazems(Set<Armazem> armazems) {
        this.armazems = armazems;
    }
    public Set<Loja> getLojas() {
        return this.lojas;
    }
    
    public void setLojas(Set<Loja> lojas) {
        this.lojas = lojas;
    }




}


